# Generated by Django 4.2.7 on 2023-11-10 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlowAPIApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowsensor',
            name='tempo_operacao',
            field=models.DateTimeField(),
        ),
    ]
